package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.Authority;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface AuthorityMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xkey_authority",
        "where authority_id = #{authorityId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_authority (authority_id, authority_type, ",
        "authority_is_del, authority_create, ",
        "authority_time)",
        "values (#{authorityId,jdbcType=VARCHAR}, #{authorityType,jdbcType=VARCHAR}, ",
        "#{authorityIsDel,jdbcType=INTEGER}, #{authorityCreate,jdbcType=VARCHAR}, ",
        "#{authorityTime,jdbcType=TIMESTAMP})"
    })
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority
     *
     * @mbggenerated
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "authority_id, authority_type, authority_is_del, authority_create, authority_time",
        "from xkey_authority",
        "where authority_id = #{authorityId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Authority selectByPrimaryKey(String authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority
     *
     * @mbggenerated
     */
    @Update({
        "update xkey_authority",
        "set authority_type = #{authorityType,jdbcType=VARCHAR},",
          "authority_is_del = #{authorityIsDel,jdbcType=INTEGER},",
          "authority_create = #{authorityCreate,jdbcType=VARCHAR},",
          "authority_time = #{authorityTime,jdbcType=TIMESTAMP}",
        "where authority_id = #{authorityId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Authority record);
}