package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.AuthorityDperation;
import org.apache.ibatis.annotations.Insert;

public interface AuthorityDperationMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority_dperation
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_authority_dperation (authority, dperation)",
        "values (#{authority,jdbcType=VARCHAR}, #{dperation,jdbcType=VARCHAR})"
    })
    int insert(AuthorityDperation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_authority_dperation
     *
     * @mbggenerated
     */
    int insertSelective(AuthorityDperation record);
}