package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.Element;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ElementMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xkey_element",
        "where element_id = #{elementId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String elementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_element (element_id, element_code, ",
        "element_is_del, element_create, ",
        "element_time)",
        "values (#{elementId,jdbcType=VARCHAR}, #{elementCode,jdbcType=VARCHAR}, ",
        "#{elementIsDel,jdbcType=INTEGER}, #{elementCreate,jdbcType=VARCHAR}, ",
        "#{elementTime,jdbcType=TIMESTAMP})"
    })
    int insert(Element record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element
     *
     * @mbggenerated
     */
    int insertSelective(Element record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "element_id, element_code, element_is_del, element_create, element_time",
        "from xkey_element",
        "where element_id = #{elementId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Element selectByPrimaryKey(String elementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Element record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element
     *
     * @mbggenerated
     */
    @Update({
        "update xkey_element",
        "set element_code = #{elementCode,jdbcType=VARCHAR},",
          "element_is_del = #{elementIsDel,jdbcType=INTEGER},",
          "element_create = #{elementCreate,jdbcType=VARCHAR},",
          "element_time = #{elementTime,jdbcType=TIMESTAMP}",
        "where element_id = #{elementId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Element record);
}