package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.ElementAuthority;
import org.apache.ibatis.annotations.Insert;

public interface ElementAuthorityMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element_authority
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_element_authority (element, authority)",
        "values (#{element,jdbcType=VARCHAR}, #{authority,jdbcType=VARCHAR})"
    })
    int insert(ElementAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_element_authority
     *
     * @mbggenerated
     */
    int insertSelective(ElementAuthority record);
}