package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.MenuAuthority;
import org.apache.ibatis.annotations.Insert;

public interface MenuAuthorityMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu_authority
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_menu_authority (menu, authority)",
        "values (#{menu,jdbcType=VARCHAR}, #{authority,jdbcType=VARCHAR})"
    })
    int insert(MenuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu_authority
     *
     * @mbggenerated
     */
    int insertSelective(MenuAuthority record);
}