package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.Menu;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface MenuMapper extends BaseMapper {

    @Select({
            "select * from xkey_menu where (menu_parent is null or menu_parent='') and menu_is_del=0 order by menu_sort"
    })
    @ResultMap("BaseResultMap")
    List<Menu> selectTopLevel();

    @Select({
            "select * from xkey_menu where menu_parent=#{menuId} order by menu_sort"
    })
    @ResultMap("BaseResultMap")
    List<Menu> selectByParent(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xkey_menu",
        "where menu_id = #{menuId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_menu (menu_id, menu_name, ",
        "menu_depcit, menu_url, ",
        "menu_parent, menu_sort, ",
        "menu_ico, menu_is_del, ",
        "menu_create, menu_time)",
        "values (#{menuId,jdbcType=VARCHAR}, #{menuName,jdbcType=VARCHAR}, ",
        "#{menuDepcit,jdbcType=VARCHAR}, #{menuUrl,jdbcType=VARCHAR}, ",
        "#{menuParent,jdbcType=VARCHAR}, #{menuSort,jdbcType=INTEGER}, ",
        "#{menuIco,jdbcType=VARCHAR}, #{menuIsDel,jdbcType=INTEGER}, ",
        "#{menuCreate,jdbcType=VARCHAR}, #{menuTime,jdbcType=TIMESTAMP})"
    })
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu
     *
     * @mbggenerated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "menu_id, menu_name, menu_depcit, menu_url, menu_parent, menu_sort, menu_ico, menu_is_del, ",
        "menu_create, menu_time",
        "from xkey_menu",
        "where menu_id = #{menuId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Menu selectByPrimaryKey(String menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_menu
     *
     * @mbggenerated
     */
    @Update({
        "update xkey_menu",
        "set menu_name = #{menuName,jdbcType=VARCHAR},",
          "menu_depcit = #{menuDepcit,jdbcType=VARCHAR},",
          "menu_url = #{menuUrl,jdbcType=VARCHAR},",
          "menu_parent = #{menuParent,jdbcType=VARCHAR},",
          "menu_sort = #{menuSort,jdbcType=INTEGER},",
          "menu_ico = #{menuIco,jdbcType=VARCHAR},",
          "menu_is_del = #{menuIsDel,jdbcType=INTEGER},",
          "menu_create = #{menuCreate,jdbcType=VARCHAR},",
          "menu_time = #{menuTime,jdbcType=TIMESTAMP}",
        "where menu_id = #{menuId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Menu record);
}