package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.Organize;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrganizeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_organize
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xkey_organize",
        "where organize_id = #{organizeId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String organizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_organize
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_organize (organize_id, organize_name, ",
        "organize_depcit, organize_parent, ",
        "organize_is_del, organize_create, ",
        "organize_time)",
        "values (#{organizeId,jdbcType=VARCHAR}, #{organizeName,jdbcType=VARCHAR}, ",
        "#{organizeDepcit,jdbcType=VARCHAR}, #{organizeParent,jdbcType=VARCHAR}, ",
        "#{organizeIsDel,jdbcType=INTEGER}, #{organizeCreate,jdbcType=VARCHAR}, ",
        "#{organizeTime,jdbcType=TIMESTAMP})"
    })
    int insert(Organize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_organize
     *
     * @mbggenerated
     */
    int insertSelective(Organize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_organize
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "organize_id, organize_name, organize_depcit, organize_parent, organize_is_del, ",
        "organize_create, organize_time",
        "from xkey_organize",
        "where organize_id = #{organizeId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Organize selectByPrimaryKey(String organizeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_organize
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Organize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_organize
     *
     * @mbggenerated
     */
    @Update({
        "update xkey_organize",
        "set organize_name = #{organizeName,jdbcType=VARCHAR},",
          "organize_depcit = #{organizeDepcit,jdbcType=VARCHAR},",
          "organize_parent = #{organizeParent,jdbcType=VARCHAR},",
          "organize_is_del = #{organizeIsDel,jdbcType=INTEGER},",
          "organize_create = #{organizeCreate,jdbcType=VARCHAR},",
          "organize_time = #{organizeTime,jdbcType=TIMESTAMP}",
        "where organize_id = #{organizeId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Organize record);
}