package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.Role;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface RoleMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_role
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xkey_role",
        "where role_id = #{roleId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_role
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_role (role_id, role_name, ",
        "role_depcit, role_is_del, ",
        "role_create, role_time)",
        "values (#{roleId,jdbcType=VARCHAR}, #{roleName,jdbcType=VARCHAR}, ",
        "#{roleDepcit,jdbcType=VARCHAR}, #{roleIsDel,jdbcType=INTEGER}, ",
        "#{roleCreate,jdbcType=VARCHAR}, #{roleTime,jdbcType=TIMESTAMP})"
    })
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_role
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_role
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "role_id, role_name, role_depcit, role_is_del, role_create, role_time",
        "from xkey_role",
        "where role_id = #{roleId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    Role selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_role
     *
     * @mbggenerated
     */
    @Update({
        "update xkey_role",
        "set role_name = #{roleName,jdbcType=VARCHAR},",
          "role_depcit = #{roleDepcit,jdbcType=VARCHAR},",
          "role_is_del = #{roleIsDel,jdbcType=INTEGER},",
          "role_create = #{roleCreate,jdbcType=VARCHAR},",
          "role_time = #{roleTime,jdbcType=TIMESTAMP}",
        "where role_id = #{roleId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Role record);
}