package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.UserRole;
import org.apache.ibatis.annotations.Insert;

public interface UserRoleMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user_role
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_user_role (user, role)",
        "values (#{user,jdbcType=VARCHAR}, #{role,jdbcType=VARCHAR})"
    })
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user_role
     *
     * @mbggenerated
     */
    int insertSelective(UserRole record);
}