package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.User;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface UserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from xkey_user",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_user (user_id, user_account, ",
        "user_password, user_is_del, ",
        "user_create, user_time)",
        "values (#{userId,jdbcType=VARCHAR}, #{userAccount,jdbcType=VARCHAR}, ",
        "#{userPassword,jdbcType=VARCHAR}, #{userIsDel,jdbcType=INTEGER}, ",
        "#{userCreate,jdbcType=VARCHAR}, #{userTime,jdbcType=TIMESTAMP})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user
     *
     * @mbggenerated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "user_id, user_account, user_password, user_is_del, user_create, user_time",
        "from xkey_user",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    @ResultMap("BaseResultMap")
    User selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user
     *
     * @mbggenerated
     */
    @Update({
        "update xkey_user",
        "set user_account = #{userAccount,jdbcType=VARCHAR},",
          "user_password = #{userPassword,jdbcType=VARCHAR},",
          "user_is_del = #{userIsDel,jdbcType=INTEGER},",
          "user_create = #{userCreate,jdbcType=VARCHAR},",
          "user_time = #{userTime,jdbcType=TIMESTAMP}",
        "where user_id = #{userId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(User record);
}