package club.ljk.comm.dao;

import club.ljk.comm.dao.base.BaseMapper;
import club.ljk.comm.model.UserOrganize;
import org.apache.ibatis.annotations.Insert;

public interface UserOrganizeMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user_organize
     *
     * @mbggenerated
     */
    @Insert({
        "insert into xkey_user_organize (user, organize)",
        "values (#{user,jdbcType=VARCHAR}, #{organize,jdbcType=VARCHAR})"
    })
    int insert(UserOrganize record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xkey_user_organize
     *
     * @mbggenerated
     */
    int insertSelective(UserOrganize record);
}