package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;
import java.util.Date;

public class Authority extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_authority.authority_id
     *
     * @mbggenerated
     */
    private String authorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_authority.authority_type
     *
     * @mbggenerated
     */
    private String authorityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_authority.authority_is_del
     *
     * @mbggenerated
     */
    private Integer authorityIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_authority.authority_create
     *
     * @mbggenerated
     */
    private String authorityCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_authority.authority_time
     *
     * @mbggenerated
     */
    private Date authorityTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_authority.authority_id
     *
     * @return the value of xkey_authority.authority_id
     *
     * @mbggenerated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_authority.authority_id
     *
     * @param authorityId the value for xkey_authority.authority_id
     *
     * @mbggenerated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_authority.authority_type
     *
     * @return the value of xkey_authority.authority_type
     *
     * @mbggenerated
     */
    public String getAuthorityType() {
        return authorityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_authority.authority_type
     *
     * @param authorityType the value for xkey_authority.authority_type
     *
     * @mbggenerated
     */
    public void setAuthorityType(String authorityType) {
        this.authorityType = authorityType == null ? null : authorityType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_authority.authority_is_del
     *
     * @return the value of xkey_authority.authority_is_del
     *
     * @mbggenerated
     */
    public Integer getAuthorityIsDel() {
        return authorityIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_authority.authority_is_del
     *
     * @param authorityIsDel the value for xkey_authority.authority_is_del
     *
     * @mbggenerated
     */
    public void setAuthorityIsDel(Integer authorityIsDel) {
        this.authorityIsDel = authorityIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_authority.authority_create
     *
     * @return the value of xkey_authority.authority_create
     *
     * @mbggenerated
     */
    public String getAuthorityCreate() {
        return authorityCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_authority.authority_create
     *
     * @param authorityCreate the value for xkey_authority.authority_create
     *
     * @mbggenerated
     */
    public void setAuthorityCreate(String authorityCreate) {
        this.authorityCreate = authorityCreate == null ? null : authorityCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_authority.authority_time
     *
     * @return the value of xkey_authority.authority_time
     *
     * @mbggenerated
     */
    public Date getAuthorityTime() {
        return authorityTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_authority.authority_time
     *
     * @param authorityTime the value for xkey_authority.authority_time
     *
     * @mbggenerated
     */
    public void setAuthorityTime(Date authorityTime) {
        this.authorityTime = authorityTime;
    }
}