package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;
import java.util.Date;

public class Dperation extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_id
     *
     * @mbggenerated
     */
    private String dperationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_name
     *
     * @mbggenerated
     */
    private String dperationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_code
     *
     * @mbggenerated
     */
    private String dperationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_url_prefix
     *
     * @mbggenerated
     */
    private String dperationUrlPrefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_parent
     *
     * @mbggenerated
     */
    private String dperationParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_is_del
     *
     * @mbggenerated
     */
    private Integer dperationIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_create
     *
     * @mbggenerated
     */
    private String dperationCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xker_dperation.dperation_time
     *
     * @mbggenerated
     */
    private Date dperationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_id
     *
     * @return the value of xker_dperation.dperation_id
     *
     * @mbggenerated
     */
    public String getDperationId() {
        return dperationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_id
     *
     * @param dperationId the value for xker_dperation.dperation_id
     *
     * @mbggenerated
     */
    public void setDperationId(String dperationId) {
        this.dperationId = dperationId == null ? null : dperationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_name
     *
     * @return the value of xker_dperation.dperation_name
     *
     * @mbggenerated
     */
    public String getDperationName() {
        return dperationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_name
     *
     * @param dperationName the value for xker_dperation.dperation_name
     *
     * @mbggenerated
     */
    public void setDperationName(String dperationName) {
        this.dperationName = dperationName == null ? null : dperationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_code
     *
     * @return the value of xker_dperation.dperation_code
     *
     * @mbggenerated
     */
    public String getDperationCode() {
        return dperationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_code
     *
     * @param dperationCode the value for xker_dperation.dperation_code
     *
     * @mbggenerated
     */
    public void setDperationCode(String dperationCode) {
        this.dperationCode = dperationCode == null ? null : dperationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_url_prefix
     *
     * @return the value of xker_dperation.dperation_url_prefix
     *
     * @mbggenerated
     */
    public String getDperationUrlPrefix() {
        return dperationUrlPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_url_prefix
     *
     * @param dperationUrlPrefix the value for xker_dperation.dperation_url_prefix
     *
     * @mbggenerated
     */
    public void setDperationUrlPrefix(String dperationUrlPrefix) {
        this.dperationUrlPrefix = dperationUrlPrefix == null ? null : dperationUrlPrefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_parent
     *
     * @return the value of xker_dperation.dperation_parent
     *
     * @mbggenerated
     */
    public String getDperationParent() {
        return dperationParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_parent
     *
     * @param dperationParent the value for xker_dperation.dperation_parent
     *
     * @mbggenerated
     */
    public void setDperationParent(String dperationParent) {
        this.dperationParent = dperationParent == null ? null : dperationParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_is_del
     *
     * @return the value of xker_dperation.dperation_is_del
     *
     * @mbggenerated
     */
    public Integer getDperationIsDel() {
        return dperationIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_is_del
     *
     * @param dperationIsDel the value for xker_dperation.dperation_is_del
     *
     * @mbggenerated
     */
    public void setDperationIsDel(Integer dperationIsDel) {
        this.dperationIsDel = dperationIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_create
     *
     * @return the value of xker_dperation.dperation_create
     *
     * @mbggenerated
     */
    public String getDperationCreate() {
        return dperationCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_create
     *
     * @param dperationCreate the value for xker_dperation.dperation_create
     *
     * @mbggenerated
     */
    public void setDperationCreate(String dperationCreate) {
        this.dperationCreate = dperationCreate == null ? null : dperationCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xker_dperation.dperation_time
     *
     * @return the value of xker_dperation.dperation_time
     *
     * @mbggenerated
     */
    public Date getDperationTime() {
        return dperationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xker_dperation.dperation_time
     *
     * @param dperationTime the value for xker_dperation.dperation_time
     *
     * @mbggenerated
     */
    public void setDperationTime(Date dperationTime) {
        this.dperationTime = dperationTime;
    }
}