package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;
import java.util.Date;

public class Element extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_element.element_id
     *
     * @mbggenerated
     */
    private String elementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_element.element_code
     *
     * @mbggenerated
     */
    private String elementCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_element.element_is_del
     *
     * @mbggenerated
     */
    private Integer elementIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_element.element_create
     *
     * @mbggenerated
     */
    private String elementCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_element.element_time
     *
     * @mbggenerated
     */
    private Date elementTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_element.element_id
     *
     * @return the value of xkey_element.element_id
     *
     * @mbggenerated
     */
    public String getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_element.element_id
     *
     * @param elementId the value for xkey_element.element_id
     *
     * @mbggenerated
     */
    public void setElementId(String elementId) {
        this.elementId = elementId == null ? null : elementId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_element.element_code
     *
     * @return the value of xkey_element.element_code
     *
     * @mbggenerated
     */
    public String getElementCode() {
        return elementCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_element.element_code
     *
     * @param elementCode the value for xkey_element.element_code
     *
     * @mbggenerated
     */
    public void setElementCode(String elementCode) {
        this.elementCode = elementCode == null ? null : elementCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_element.element_is_del
     *
     * @return the value of xkey_element.element_is_del
     *
     * @mbggenerated
     */
    public Integer getElementIsDel() {
        return elementIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_element.element_is_del
     *
     * @param elementIsDel the value for xkey_element.element_is_del
     *
     * @mbggenerated
     */
    public void setElementIsDel(Integer elementIsDel) {
        this.elementIsDel = elementIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_element.element_create
     *
     * @return the value of xkey_element.element_create
     *
     * @mbggenerated
     */
    public String getElementCreate() {
        return elementCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_element.element_create
     *
     * @param elementCreate the value for xkey_element.element_create
     *
     * @mbggenerated
     */
    public void setElementCreate(String elementCreate) {
        this.elementCreate = elementCreate == null ? null : elementCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_element.element_time
     *
     * @return the value of xkey_element.element_time
     *
     * @mbggenerated
     */
    public Date getElementTime() {
        return elementTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_element.element_time
     *
     * @param elementTime the value for xkey_element.element_time
     *
     * @mbggenerated
     */
    public void setElementTime(Date elementTime) {
        this.elementTime = elementTime;
    }
}