package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;

public class MenuAuthority extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu_authority.menu
     *
     * @mbggenerated
     */
    private String menu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu_authority.authority
     *
     * @mbggenerated
     */
    private String authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu_authority.menu
     *
     * @return the value of xkey_menu_authority.menu
     *
     * @mbggenerated
     */
    public String getMenu() {
        return menu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu_authority.menu
     *
     * @param menu the value for xkey_menu_authority.menu
     *
     * @mbggenerated
     */
    public void setMenu(String menu) {
        this.menu = menu == null ? null : menu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu_authority.authority
     *
     * @return the value of xkey_menu_authority.authority
     *
     * @mbggenerated
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu_authority.authority
     *
     * @param authority the value for xkey_menu_authority.authority
     *
     * @mbggenerated
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }
}