package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;
import org.hibernate.validator.constraints.NotBlank;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class Menu extends BaseModel implements Serializable {
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_id
     *
     * @mbggenerated
     */
    private String menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_name
     *
     * @mbggenerated
     */
    @NotBlank
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_depcit
     *
     * @mbggenerated
     */
    private String menuDepcit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_url
     *
     * @mbggenerated
     */
    private String menuUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_parent
     *
     * @mbggenerated
     */
    private String menuParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_sort
     *
     * @mbggenerated
     */
    private Integer menuSort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_ico
     *
     * @mbggenerated
     */
    private String menuIco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_is_del
     *
     * @mbggenerated
     */
    private Integer menuIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_create
     *
     * @mbggenerated
     */
    private String menuCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_menu.menu_time
     *
     * @mbggenerated
     */
    private Date menuTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_id
     *
     * @return the value of xkey_menu.menu_id
     *
     * @mbggenerated
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_id
     *
     * @param menuId the value for xkey_menu.menu_id
     *
     * @mbggenerated
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_name
     *
     * @return the value of xkey_menu.menu_name
     *
     * @mbggenerated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_name
     *
     * @param menuName the value for xkey_menu.menu_name
     *
     * @mbggenerated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_depcit
     *
     * @return the value of xkey_menu.menu_depcit
     *
     * @mbggenerated
     */
    public String getMenuDepcit() {
        return menuDepcit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_depcit
     *
     * @param menuDepcit the value for xkey_menu.menu_depcit
     *
     * @mbggenerated
     */
    public void setMenuDepcit(String menuDepcit) {
        this.menuDepcit = menuDepcit == null ? null : menuDepcit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_url
     *
     * @return the value of xkey_menu.menu_url
     *
     * @mbggenerated
     */
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_url
     *
     * @param menuUrl the value for xkey_menu.menu_url
     *
     * @mbggenerated
     */
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_parent
     *
     * @return the value of xkey_menu.menu_parent
     *
     * @mbggenerated
     */
    public String getMenuParent() {
        return menuParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_parent
     *
     * @param menuParent the value for xkey_menu.menu_parent
     *
     * @mbggenerated
     */
    public void setMenuParent(String menuParent) {
        this.menuParent = menuParent == null ? null : menuParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_sort
     *
     * @return the value of xkey_menu.menu_sort
     *
     * @mbggenerated
     */
    public Integer getMenuSort() {
        return menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_sort
     *
     * @param menuSort the value for xkey_menu.menu_sort
     *
     * @mbggenerated
     */
    public void setMenuSort(Integer menuSort) {
        this.menuSort = menuSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_ico
     *
     * @return the value of xkey_menu.menu_ico
     *
     * @mbggenerated
     */
    public String getMenuIco() {
        return menuIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_ico
     *
     * @param menuSort the value for xkey_menu.menu_ico
     *
     * @mbggenerated
     */
    public void setMenuIco(String menuIco) {
        this.menuIco = menuIco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_is_del
     *
     * @return the value of xkey_menu.menu_is_del
     *
     * @mbggenerated
     */
    public Integer getMenuIsDel() {
        return menuIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_is_del
     *
     * @param menuIsDel the value for xkey_menu.menu_is_del
     *
     * @mbggenerated
     */
    public void setMenuIsDel(Integer menuIsDel) {
        this.menuIsDel = menuIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_create
     *
     * @return the value of xkey_menu.menu_create
     *
     * @mbggenerated
     */
    public String getMenuCreate() {
        return menuCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_create
     *
     * @param menuCreate the value for xkey_menu.menu_create
     *
     * @mbggenerated
     */
    public void setMenuCreate(String menuCreate) {
        this.menuCreate = menuCreate == null ? null : menuCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_menu.menu_time
     *
     * @return the value of xkey_menu.menu_time
     *
     * @mbggenerated
     */
    public Date getMenuTime() {
        return menuTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_menu.menu_time
     *
     * @param menuTime the value for xkey_menu.menu_time
     *
     * @mbggenerated
     */
    public void setMenuTime(Date menuTime) {
        this.menuTime = menuTime;
    }


    private Menu menu;

    private List<Menu> menus;

    public Menu getMenu() {
        return menu;
    }

    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public List<Menu> getMenus() {
        return menus;
    }

    public void setMenus(List<Menu> menus) {
        this.menus = menus;
    }
}