package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;
import java.util.Date;

public class Organize extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_id
     *
     * @mbggenerated
     */
    private String organizeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_name
     *
     * @mbggenerated
     */
    private String organizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_depcit
     *
     * @mbggenerated
     */
    private String organizeDepcit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_parent
     *
     * @mbggenerated
     */
    private String organizeParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_is_del
     *
     * @mbggenerated
     */
    private Integer organizeIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_create
     *
     * @mbggenerated
     */
    private String organizeCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize.organize_time
     *
     * @mbggenerated
     */
    private Date organizeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_id
     *
     * @return the value of xkey_organize.organize_id
     *
     * @mbggenerated
     */
    public String getOrganizeId() {
        return organizeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_id
     *
     * @param organizeId the value for xkey_organize.organize_id
     *
     * @mbggenerated
     */
    public void setOrganizeId(String organizeId) {
        this.organizeId = organizeId == null ? null : organizeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_name
     *
     * @return the value of xkey_organize.organize_name
     *
     * @mbggenerated
     */
    public String getOrganizeName() {
        return organizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_name
     *
     * @param organizeName the value for xkey_organize.organize_name
     *
     * @mbggenerated
     */
    public void setOrganizeName(String organizeName) {
        this.organizeName = organizeName == null ? null : organizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_depcit
     *
     * @return the value of xkey_organize.organize_depcit
     *
     * @mbggenerated
     */
    public String getOrganizeDepcit() {
        return organizeDepcit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_depcit
     *
     * @param organizeDepcit the value for xkey_organize.organize_depcit
     *
     * @mbggenerated
     */
    public void setOrganizeDepcit(String organizeDepcit) {
        this.organizeDepcit = organizeDepcit == null ? null : organizeDepcit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_parent
     *
     * @return the value of xkey_organize.organize_parent
     *
     * @mbggenerated
     */
    public String getOrganizeParent() {
        return organizeParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_parent
     *
     * @param organizeParent the value for xkey_organize.organize_parent
     *
     * @mbggenerated
     */
    public void setOrganizeParent(String organizeParent) {
        this.organizeParent = organizeParent == null ? null : organizeParent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_is_del
     *
     * @return the value of xkey_organize.organize_is_del
     *
     * @mbggenerated
     */
    public Integer getOrganizeIsDel() {
        return organizeIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_is_del
     *
     * @param organizeIsDel the value for xkey_organize.organize_is_del
     *
     * @mbggenerated
     */
    public void setOrganizeIsDel(Integer organizeIsDel) {
        this.organizeIsDel = organizeIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_create
     *
     * @return the value of xkey_organize.organize_create
     *
     * @mbggenerated
     */
    public String getOrganizeCreate() {
        return organizeCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_create
     *
     * @param organizeCreate the value for xkey_organize.organize_create
     *
     * @mbggenerated
     */
    public void setOrganizeCreate(String organizeCreate) {
        this.organizeCreate = organizeCreate == null ? null : organizeCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize.organize_time
     *
     * @return the value of xkey_organize.organize_time
     *
     * @mbggenerated
     */
    public Date getOrganizeTime() {
        return organizeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize.organize_time
     *
     * @param organizeTime the value for xkey_organize.organize_time
     *
     * @mbggenerated
     */
    public void setOrganizeTime(Date organizeTime) {
        this.organizeTime = organizeTime;
    }
}