package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;

public class OrganizeRole extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize_role.organize
     *
     * @mbggenerated
     */
    private String organize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_organize_role.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize_role.organize
     *
     * @return the value of xkey_organize_role.organize
     *
     * @mbggenerated
     */
    public String getOrganize() {
        return organize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize_role.organize
     *
     * @param organize the value for xkey_organize_role.organize
     *
     * @mbggenerated
     */
    public void setOrganize(String organize) {
        this.organize = organize == null ? null : organize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_organize_role.role
     *
     * @return the value of xkey_organize_role.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_organize_role.role
     *
     * @param role the value for xkey_organize_role.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}