package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;
import java.util.Date;

public class User extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user.user_account
     *
     * @mbggenerated
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user.user_password
     *
     * @mbggenerated
     */
    private String userPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user.user_is_del
     *
     * @mbggenerated
     */
    private Integer userIsDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user.user_create
     *
     * @mbggenerated
     */
    private String userCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user.user_time
     *
     * @mbggenerated
     */
    private Date userTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user.user_id
     *
     * @return the value of xkey_user.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user.user_id
     *
     * @param userId the value for xkey_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user.user_account
     *
     * @return the value of xkey_user.user_account
     *
     * @mbggenerated
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user.user_account
     *
     * @param userAccount the value for xkey_user.user_account
     *
     * @mbggenerated
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount == null ? null : userAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user.user_password
     *
     * @return the value of xkey_user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user.user_password
     *
     * @param userPassword the value for xkey_user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user.user_is_del
     *
     * @return the value of xkey_user.user_is_del
     *
     * @mbggenerated
     */
    public Integer getUserIsDel() {
        return userIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user.user_is_del
     *
     * @param userIsDel the value for xkey_user.user_is_del
     *
     * @mbggenerated
     */
    public void setUserIsDel(Integer userIsDel) {
        this.userIsDel = userIsDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user.user_create
     *
     * @return the value of xkey_user.user_create
     *
     * @mbggenerated
     */
    public String getUserCreate() {
        return userCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user.user_create
     *
     * @param userCreate the value for xkey_user.user_create
     *
     * @mbggenerated
     */
    public void setUserCreate(String userCreate) {
        this.userCreate = userCreate == null ? null : userCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user.user_time
     *
     * @return the value of xkey_user.user_time
     *
     * @mbggenerated
     */
    public Date getUserTime() {
        return userTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user.user_time
     *
     * @param userTime the value for xkey_user.user_time
     *
     * @mbggenerated
     */
    public void setUserTime(Date userTime) {
        this.userTime = userTime;
    }
}