package club.ljk.comm.model;

import club.ljk.comm.model.base.BaseModel;

public class UserOrganize extends BaseModel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user_organize.user
     *
     * @mbggenerated
     */
    private String user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xkey_user_organize.organize
     *
     * @mbggenerated
     */
    private String organize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user_organize.user
     *
     * @return the value of xkey_user_organize.user
     *
     * @mbggenerated
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user_organize.user
     *
     * @param user the value for xkey_user_organize.user
     *
     * @mbggenerated
     */
    public void setUser(String user) {
        this.user = user == null ? null : user.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xkey_user_organize.organize
     *
     * @return the value of xkey_user_organize.organize
     *
     * @mbggenerated
     */
    public String getOrganize() {
        return organize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xkey_user_organize.organize
     *
     * @param organize the value for xkey_user_organize.organize
     *
     * @mbggenerated
     */
    public void setOrganize(String organize) {
        this.organize = organize == null ? null : organize.trim();
    }
}